spring:
  application.name: users-ws
  h2.console:
    enabled: true
    settings.web-allow-others: true
    
server.port: 809${SEQ_NO:1}
  
eureka:
  instance:
    instanceId: ${spring.application.name}-${random.uuid}