spring.application.name: zuul-server
server.port: ${PORT:8081}

eureka:
  instance:
    instanceId: ${spring.application.name}-${random.uuid}

uri-zuul:
  h2console:
    path: ${domain.users}/h2-console/**
  user:
    signup: ${domain.users}/auth
    signin: ${domain.users}/auth/signin