spring:
  h2: 
    console:
      enabled: true
      settings: 
        web-allow-others: true 

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    instanceId: ${spring.application.name}-${server.port}
  